name: 10 Deploy Infrastructure

on:
  schedule:
    - cron: "0 20 * * *"  # 6:00 AM UTC+10
    - cron: "0 4 * * *"   # 2:00 PM UTC+10
  push:
    branches: [main]
    paths:
      - "bicep/**"
      - ".github/workflows/10_deploy_iac.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4

      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep
        working-directory: bicep
        run: |
          az deployment group create \
            --name 'opc-shared-dev' \
            --resource-group 'rg-playground-shared' \
            --template-file './main.bicep' \
            --parameters './main.bicepparam' 
